/* ── Room definitions ─────────────────────────────────────────────
   Tầng 6: Room1(Small), Room2(MD), Room3(Small), Room4(MC), Big
   Tầng 5: Room1(MD), Room2(MC), Room3(Small), Room4(Small), Big
   Tầng 4: Cine1, Cine2, Cine3, Suite1, Suite2
   ─────────────────────────────────────────────────────────────── */
const ROOMS = [
  /* ═ TẦNG 6 ═ */
  { id:'t6-room1', name:'Room 1', floor:6, type:'small',
    emoji:'🎮', badge:'Small', badgeClass:'badge-white',
    desc:'Phòng Small private tầng 6 — ấm cúng cho 1–2 người.',
    capacity:'1–2 người', features:['Small','1–2 người','Boardgame free','Tầng 6'],
    price:59, gradient:'linear-gradient(135deg,#1a1000,#0c0c0c)' },
  { id:'t6-room2', name:'Room 2', floor:6, type:'medium-deluxe',
    emoji:'⭐', badge:'Medium Deluxe', badgeClass:'badge-gold',
    desc:'Phòng Medium Deluxe tầng 6 — rộng rãi cho 1–4 người. Phổ biến nhất!',
    capacity:'1–4 người', features:['Medium Deluxe','1–4 người','Boardgame free','Tầng 6'],
    price:99, gradient:'linear-gradient(135deg,#1e1800,#0c0c0c)' },
  { id:'t6-room3', name:'Room 3', floor:6, type:'small',
    emoji:'🎮', badge:'Small', badgeClass:'badge-white',
    desc:'Phòng Small private tầng 6 — riêng tư cho 1–2 người hẹn hò.',
    capacity:'1–2 người', features:['Small','1–2 người','Boardgame free','Tầng 6'],
    price:59, gradient:'linear-gradient(135deg,#1a1000,#0c0c0c)' },
  { id:'t6-room4', name:'Room 4', floor:6, type:'medium-classic',
    emoji:'🕹️', badge:'Medium Classic', badgeClass:'badge-gray',
    desc:'Phòng Medium Classic tầng 6 — cân bằng không gian & giá cho nhóm 3.',
    capacity:'1–3 người', features:['Medium Classic','1–3 người','Boardgame free','Tầng 6'],
    price:79, gradient:'linear-gradient(135deg,#0c1a00,#0c0c0c)' },
  { id:'t6-big', name:'Big Room', floor:6, type:'big',
    emoji:'🎉', badge:'Big Room', badgeClass:'badge-gold',
    desc:'Phòng lớn nhất tầng 6 — sinh nhật, nhóm đông tới 8 người.',
    capacity:'1–8 người (tính 6)', features:['Big Room','1–8 người','Boardgame free','Tầng 6'],
    price:139, gradient:'linear-gradient(135deg,#1a1500,#0c0c0c)' },

  /* ═ TẦNG 5 ═ */
  { id:'t5-room1', name:'Room 1', floor:5, type:'medium-deluxe',
    emoji:'⭐', badge:'Medium Deluxe', badgeClass:'badge-gold',
    desc:'Phòng Medium Deluxe tầng 5 — rộng, thoải mái cho 1–4 người.',
    capacity:'1–4 người', features:['Medium Deluxe','1–4 người','Boardgame free','Tầng 5'],
    price:99, gradient:'linear-gradient(135deg,#1e1800,#0c0c0c)' },
  { id:'t5-room2', name:'Room 2', floor:5, type:'medium-classic',
    emoji:'🕹️', badge:'Medium Classic', badgeClass:'badge-gray',
    desc:'Phòng Medium Classic tầng 5 — lựa chọn tốt cho nhóm 3 người.',
    capacity:'1–3 người', features:['Medium Classic','1–3 người','Boardgame free','Tầng 5'],
    price:79, gradient:'linear-gradient(135deg,#0c1a00,#0c0c0c)' },
  { id:'t5-room3', name:'Room 3', floor:5, type:'small',
    emoji:'🎮', badge:'Small', badgeClass:'badge-white',
    desc:'Phòng Small private tầng 5 — nhỏ gọn, riêng tư cho 1–2 người.',
    capacity:'1–2 người', features:['Small','1–2 người','Boardgame free','Tầng 5'],
    price:59, gradient:'linear-gradient(135deg,#1a1000,#0c0c0c)' },
  { id:'t5-room4', name:'Room 4', floor:5, type:'small',
    emoji:'🎮', badge:'Small', badgeClass:'badge-white',
    desc:'Phòng Small private tầng 5 — hoàn hảo cho couple hoặc solo chill.',
    capacity:'1–2 người', features:['Small','1–2 người','Boardgame free','Tầng 5'],
    price:59, gradient:'linear-gradient(135deg,#1a1000,#0c0c0c)' },
  { id:'t5-big', name:'Big Room', floor:5, type:'big',
    emoji:'🎉', badge:'Big Room', badgeClass:'badge-gold',
    desc:'Phòng lớn nhất tầng 5 — party game cho nhóm đến 8 người.',
    capacity:'1–8 người (tính 6)', features:['Big Room','1–8 người','Boardgame free','Tầng 5'],
    price:139, gradient:'linear-gradient(135deg,#1a1500,#0c0c0c)' },

  /* ═ TẦNG 4 — CINE BOX ═ */
  { id:'cine-1', name:'Cine 1', floor:4, type:'cine',
    emoji:'🎬', badge:'Cine', badgeClass:'badge-red',
    desc:'Phòng Cine tầng 4 — màn chiếu lớn, âm thanh chuẩn rạp cho 1–3 người.',
    capacity:'1–3 người', features:['Cine Box','Màn chiếu lớn','Netflix/Disney+','Tầng 4'],
    price:75, gradient:'linear-gradient(135deg,#1a0010,#0c0c0c)' },
  { id:'cine-2', name:'Cine 2', floor:4, type:'cine',
    emoji:'🎬', badge:'Cine', badgeClass:'badge-red',
    desc:'Phòng Cine tầng 4 — xem phim riêng tư, loa surround cho 1–3 người.',
    capacity:'1–3 người', features:['Cine Box','Loa Surround','Netflix/Disney+','Tầng 4'],
    price:75, gradient:'linear-gradient(135deg,#1a0010,#0c0c0c)' },
  { id:'cine-3', name:'Cine 3', floor:4, type:'cine',
    emoji:'🎬', badge:'Cine', badgeClass:'badge-red',
    desc:'Phòng Cine tầng 4 — trải nghiệm phim 100% riêng tư cho 1–3 người.',
    capacity:'1–3 người', features:['Cine Box','Màn chiếu lớn','Netflix/Disney+','Tầng 4'],
    price:75, gradient:'linear-gradient(135deg,#1a0010,#0c0c0c)' },
  { id:'suite-1', name:'Suite 1', floor:4, type:'suite',
    emoji:'🌟', badge:'Suite', badgeClass:'badge-gold',
    desc:'Suite Cine tầng 4 — màn chiếu lớn + sofa đôi cao cấp cho 1–4 người.',
    capacity:'1–4 người', features:['Suite Cine','Sofa đôi','Netflix/Disney+','Tầng 4'],
    price:99, gradient:'linear-gradient(135deg,#1e1800,#0c0c0c)' },
  { id:'suite-2', name:'Suite 2', floor:4, type:'suite',
    emoji:'🌟', badge:'Suite', badgeClass:'badge-gold',
    desc:'Suite Cine tầng 4 — sang trọng nhất, ghế recliner cao cấp cho 1–4 người.',
    capacity:'1–4 người', features:['Suite Cine','Ghế Recliner','Netflix/Disney+','Tầng 4'],
    price:99, gradient:'linear-gradient(135deg,#1e1800,#0c0c0c)' },
];

const TYPE_LABELS = {
  'small':          '🎮 Small',
  'medium-classic': '🕹️ Medium Classic',
  'medium-deluxe':  '⭐ Medium Deluxe',
  'big':            '🎉 Big Room',
  'cine':           '🎬 Cine',
  'suite':          '🌟 Suite',
};

const FLOOR_META = {
  6: { label:'Tầng 6', desc:'Small · Medium Classic · Medium Deluxe · Big Room' },
  5: { label:'Tầng 5', desc:'Small · Medium Classic · Medium Deluxe · Big Room' },
  4: { label:'Tầng 4 — Cine Box', desc:'Cine 1 · Cine 2 · Cine 3 · Suite 1 · Suite 2' },
};
